build:
  image: centos:7
  commands:
    - echo "totes tested"
    - echo "for reals"

publish:
  docker:
    username: chuyskywalker
    password: $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
    repo: chuyskywalker/murmur
