
publish:
  docker:
    username: chuyskywalker
    password: $$DOCKERHUB_PASS
    email: $$DOCKERHUB_EMAIL
    repo: chuyskywalker/murmur
    storage_driver: vfs
    tag:
      - latest
      - "$$BUILD_NUMBER-$$COMMIT"
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
