
build:
  image: chuyskywalker/centos7docker:3-6b54c28c5e04a0d6e3171daeff50b6fb657c5389
  environment:
    - DOCKER_HOST=unix:///tmp/host.sock
    - IMAGEID=chuyskywalker/murmur:$$BUILD_NUMBER-$$COMMIT
    - DOCKERHUB_USER=$$DOCKERHUB_USER
    - DOCKERHUB_PASS=$$DOCKERHUB_PASS
    - DOCKERHUB_EMAIL=$$DOCKERHUB_EMAIL
  volumes:
    - /var/run/docker.sock:/tmp/host.sock:rw
  commands:
    - docker build -t "$IMAGEID" .
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS" -e "$DOCKERHUB_EMAIL"
    - docker push "$IMAGEID"
