
build:
  image: centos:7
  environment:
    - DOCKER_HOST=unix:///var/run/host.sock
    - IMAGEID=chuyskywalker/murmur:$$BUILD_NUMBER-$$COMMIT
  commands:
    - printenv
    - |
      cat <<'EOF' > /etc/yum.repos.d/docker.repo
      [dockerrepo]
      name=Docker Repository
      baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
      enabled=1
      gpgcheck=1
      gpgkey=https://yum.dockerproject.org/gpg
      EOF
    - yum install -y docker-engine
    - docker build -t "$IMAGEID" .
    - docker login -u $$DOCKERHUB_USER -p $$DOCKERHUB_PASS -e $$DOCKERHUB_EMAIL
    - docker push "$IMAGEID"
  volumes:
    - /var/run/docker.sock:/var/run/host.sock:rw

#publish:
#  docker:
#    username: chuyskywalker
#    password: $$DOCKERHUB_PASS
#    email: $$DOCKERHUB_EMAIL
#    repo: chuyskywalker/murmur
#    storage_driver: overlay
#    tag:
#      - latest
#      - "$$BUILD_NUMBER-$$COMMIT"
#    load: docker/image.tar
#    save:
#      destination: docker/image.tar
#
#cache:
#  mount:
#    - docker/image.tar
